# Generated by Django 4.2.1 on 2023-05-22 10:44

import accounts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=accounts.utils.get_default_avatar, upload_to=accounts.utils.get_avatar_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='percent',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Скидка в процентах'),
        ),
    ]
