# Generated by Django 4.2.1 on 2023-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sale_end_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
    ]
