# Generated by Django 4.2.1 on 2023-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение от менеджера'),
        ),
    ]
