# Generated by Django 4.2.1 on 2023-05-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_manager_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('admin', 'admin')], default='user', max_length=50),
        ),
    ]
