# Generated by Django 4.2.1 on 2023-05-26 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history_manager', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history_to', to=settings.AUTH_USER_MODEL, verbose_name='Кому выдал')),
            ],
            options={
                'verbose_name': 'Чек на выдачу бонусов',
                'verbose_name_plural': 'Истории выдачи бонусов',
            },
        ),
    ]
