# Generated by Django 4.2.1 on 2023-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество бонусов'),
        ),
    ]
