# Generated by Django 4.2.1 on 2023-05-26 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_paymenthistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
