# Generated by Django 4.2.1 on 2023-05-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_paymenthistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='manager_message',
        ),
    ]
