# Generated by Django 4.2.1 on 2023-05-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default='', max_length=500, verbose_name='Текст сообщения'),
        ),
    ]
