# Generated by Django 4.2.1 on 2023-05-27 14:23

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_bot_setup',
            field=models.BooleanField(default=False, verbose_name='Требуется установка бота на сервер'),
        ),
        migrations.AddField(
            model_name='order',
            name='need_server_setup',
            field=models.BooleanField(default=False, verbose_name='Требуется настройка сервера'),
        ),
        migrations.AddField(
            model_name='order',
            name='tz_file',
            field=models.FileField(default=None, null=True, upload_to=accounts.utils.get_order_tz_path, verbose_name='Файл с техническим заданием'),
        ),
    ]
