# Generated by Django 4.2.1 on 2023-05-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_order_need_bot_setup_order_need_server_setup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sale', verbose_name='Скидка'),
        ),
    ]
