# Generated by Django 4.2.1 on 2023-05-27 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_order_promo_order_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))), null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sale', verbose_name='Скидка'),
        ),
    ]
