# Generated by Django 4.2.1 on 2023-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_order_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='Email для чека'),
        ),
    ]
