# Generated by Django 4.2.1 on 2023-05-28 14:06

import accounts.utils
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_order_promo_order_need_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='answer_link',
            field=models.CharField(default='', max_length=255, validators=[accounts.validators.github_link_validator], verbose_name='Ссылка на github репозиторий с проектом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='need_server_setup',
            field=models.BooleanField(default=False, verbose_name='Требуется установка/настройка сервера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tz_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=accounts.utils.get_order_tz_path, verbose_name='Файл с техническим заданием'),
        ),
    ]
