# Generated by Django 4.2.1 on 2023-05-28 14:22

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_order_answer_link_alter_order_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='answer_link',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[accounts.validators.github_link_validator], verbose_name='Ссылка на github репозиторий с проектом'),
        ),
    ]
