# Generated by Django 4.2.1 on 2023-05-31 19:16

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=accounts.utils.get_util_file_path, verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'Утилита',
                'verbose_name_plural': 'Утилиты',
            },
        ),
    ]
