# Generated by Django 4.2.1 on 2023-05-31 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_utilit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidUtils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('util', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utilit', verbose_name='Утилита')),
            ],
            options={
                'verbose_name': 'Купленная утилита',
                'verbose_name_plural': 'Купленные утилиты',
            },
        ),
    ]
