# Generated by Django 4.2.1 on 2023-05-31 23:44

import accounts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_paidutils'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilit',
            name='instruction',
            field=models.FileField(blank=True, default=None, null=True, upload_to=accounts.utils.get_util_instruction_path, validators=[django.core.validators.FileExtensionValidator(['html'])], verbose_name='Инструкция'),
        ),
    ]
